### ISSUE TITLE
Web service requests sometimes throw errors or crash

### ISSUE THREAD

**Issue by mventimi** [ambiverse-nlu/ambiverse-nlu#19]
First, thanks for open sourcing such an impressive suite of tools!

We're running into some errors and crashes as we put AmbiverseNLU through its paces, and I wanted to see if you could provide any insight on where we're going wrong. We're running on an EC2 m5n.4xlarge instance (16 core, 64G mem, 1TB HDD, 18k IOPS).

The installation went without incident. We installed the docker containers individually per the instructions on Docker Hub, The docker-compose script timed out on AmbiverseNLU waiting for the PostgreSQL install to complete, but we opted to reinstall manually instead of changing the timeout.

The web service starts up fine and processes most request without incident. However, we are seeing some issues:

1. One or more of the following errors occur when processing some requests:
`2020-01-10 07:17:37,550 [qtp1359212194-54088] INFO  custom.aes.ClausIEAnalysisEngine:119  - Exception at ClausIEAnalysisEngine: null`
These seem innocuous--AmbiverseNLU still returns a valid set of entities. Does this indicate a bigger issue? We did wonder if it indicates some kind of memory leak or other problem that could contribute to the below issues.

2. ~3% of the documents we submit fail. This occurs after 16 consecutive errors as shown in #1 above, at which point the stack dump shown below prints and AmbiverseNLU responds with an empty JSON object ("{}"). This problem is 100% reproducible with specific text, and relatively minor changes to the text can make the problem disappear.
```
2020-01-10 07:25:45,412 [qtp1359212194-49842] ERROR util.impl.JSR47Logger_impl:324  - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
        at de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.uima.custom.aes.ClausIEAnalysisEngine.process(ClausIEAnalysisEngine.java:121)
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
...deleted...
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
2020-01-10 07:25:45,413 [qtp1359212194-49842] ERROR util.impl.JSR47Logger_impl:324  - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
        at de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.uima.custom.aes.ClausIEAnalysisEngine.process(ClausIEAnalysisEngine.java:121)
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
...deleted...
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.processor.UnprocessableDocumentException
        at de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.processor.DocumentProcessor.process(DocumentProcessor.java:72)
        at de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.service.web.resource.impl.AnalyzeResourceWithFactsImpl.postAnalyze(AnalyzeResourceWithFactsImpl.java:95)
...deleted...
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
2020-01-10 07:25:45,415 [qtp1359212194-49842] ERROR resource.impl.AnalyzeResourceWithFactsImpl:112  - (221) AnalyzeInput{docId='doc1', language='en', text='...document text...', confidenceThreshold=null, coherentDocument=null, annotatedMentions=null}
2020-01-10 07:25:45,416 [qtp1359212194-49842] ERROR resource.impl.AnalyzeResourceWithFactsImpl:113  - ERROR MESSAGE: null
```

3. We are running documents through AmbiverseNLU as fast as it can process them--roughly every 3-4 seconds. As it is running, we use `docker logs` and `htop` to monitor the system in real-time. After many hours of processing, the process runs out of memory and core dumps. The beginning of the log is shown below. We have not noticed a memory leak, but the restarts have occurred overnight so we can't be sure. We are now logging free memory, so we should be able to provide more definitive data if a memory leak is occurring.
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 3775922176 bytes for committing reserved memory.
# Can not save log file, dump to screen..
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 3775922176 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   In 32 bit mode, the process size limit was hit
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Use 64 bit Java on a 64 bit OS
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2643), pid=1, tid=0x00007f625577e700
#
# JRE version: OpenJDK Runtime Environment (8.0_141-b15) (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.141-b15 mixed mode linux-amd64 )
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f6b56600000, 3775922176, 0) failed; error='Cannot allocate memory' (errno=12)
# Core dump written. Default location: /ambiverse-nlu/core or core.1
#
```

4. After the above restart occurs, the ConceptSpotters are initialized and dummy docs are run for each language, and the Jetty service starts up. After this, six errors occur similar to:
`[WARNING] Illegal character 0x16 in state=START for buffer HeapByteBuffer@7a822f53[p=1,l=215,c=8192,r=214]={\x16<<<\x03\x01\x00\xD2\x01\x00\x00\xCe\x03\x03\xF1\xA1kE\xB4\xB8\xE8...\x03\x02\x03\x03\x02\x01\x02\x02\x02\x03\x00\x0f\x00\x01\x01>>>v20170414)\r\n\r\n:80...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}`
At this point, when we send a request to the web service, the ConceptSpotters are reinitialized. This process takes about 10 minutes, after which the response is returned. After that, requests are processed normally. This does not seem to occur when the server is initially installed and brought up. We were wondering if there is some cleanup we need to do on startup to prevent this, and if it's a problem.

Apologies for the involved issue. Please let us know if there is any additional information or logs you need to look into these. Also, if it is easier for us to split this into four separate issues, we'll be happy to do so. Thanks in advance!

**Comment by hoffart** [comment]
Thanks for the detailed issue description!

First, some clarification questions: 
1. Do you actually need ClausIE, which does open information extraction, i.e. extracts subject-predicate-object triples?
2. Same with ConceptSpotter, do you actually want to annotate concepts (not named entities)?

ConceptSpotter is a very new component which might need some more testing paces.

Regarding the ClausIE error, it would be great if you could provide the text that causes the error, so we can reproduce it more easily.

Thanks, Johannes

**Comment by mventimi** [comment]
Right now we don't need ClausIE or ConceptSpotter, although we will in the future. I didn't know whether they were used by KnowNER and AIDA, or whether they were adding significant overhead. Since the results we get back from the web service are a list of matches and entities, I wasn't even sure that they were doing much.

If it's better for us to disable ClausIE and ConceptSpotter right now, either for stability or performance, then that might be the best approach. We can keep an instance running with everything enabled to help you investigate the above issues if needed.

Below is a snippet of text that causes an error. I tested it using 'curl localhost' requests. (Apologies for the subject matter--we're running text from random web pages through the engine, and this was simply the shortest snippet I could find that failed.)
`Most already know. I would never live there again. The reason Canada has so many professional immigrants. Our country is awesome. I live far better here than I ever did in the USA. We get paid better; our cities are cleaner. We don’t work as hard. Our crime is low. Our air and water are cleaner. Our Healthcare is free! We are definitely healthier than Americans, by a long shot. And, everybody loves Canadians because we are so nice. What’s not to love? Anywhere is better than the US. Period. You people are all in denial. You ar`
This text fails reliably. If I either replace the "r" in the last character with a "t", or delete it entirely, it passes reliably.

Please let me know if you're able to reproduce the issue with the above text. If it will help, I can also send you credentials to access one of our instances.

**Comment by hoffart** [comment]
Thanks for sending the failing text, we will have a look.

Regarding dependencies:
- AIDA depends on NER, PoS, Tokens (which can be filled by KnowNER or any other NER module).
- ClausIE depends on a syntactically parsed sentence, PoS, Tokens, so will slow down processing
- ConceptSpotter depends on PoS, Tokens

So, if you only need entities, simply running token, pos, ner, aida should be the right way. If you are calling the web service, please use the /entitylinking/analyze endpoint, which should be doing this by default.

**Comment by mventimi** [comment]
I tried using the `entitylinking` endpoint, and that has so far eliminated the `NullPointerException` issues (#2 in my original comment). I do have one question about what I'm seeing in the logs, though. For each document, it shows two preparation and disambiguation steps:

```
2020-01-13 21:57:37,148 [qtp1359212194-1617] INFO  entitylinking.preparation.Preparator:53  - Document '300523508486' prepared in 4178.0ms.
2020-01-13 21:57:53,506 [qtp1359212194-1617] INFO  nlu.entitylinking.Disambiguator:101  - Document '300523508486' disambiguated in 16358.0ms (11 chunks, 283 mentions).
2020-01-13 21:57:56,758 [qtp1359212194-1617] INFO  entitylinking.preparation.Preparator:53  - Document '300523508486' prepared in 3214.0ms.
2020-01-13 21:58:37,670 [qtp1359212194-1617] INFO  nlu.entitylinking.Disambiguator:101  - Document '300523508486' disambiguated in 40912.0ms (11 chunks, 1527 mentions).
```

I'm curious as to how this maps to the steps you mentioned above (Token, PoS, NER, AIDA). Is there a two pass process?

Also, should I expect the performance of the entity linker to scale linearly with document length and/or number of recognized entities? The above example was 26527 characters or 3819 words, and AmbiverseNLU found 554 entities.

**Comment by mventimi** [comment]
One additional comment--I've been running via the `entitylinking` endpoint all day now, and I am still seeing the memory leak (#&#8288;3 in my original comment). Things are now running more smoothly without the ClausIE crashes, but I think that's causing the web service to crash more frequently--every 2-3 hours or so. I'm assuming it's the AmbiverseNLU container and not PostgreSQL that's causing the problem, but I'll monitor `docker stats` to see if I can catch the problem.

**Comment by dmilcevski** [comment]
Regarding your previous comment, the output shows that it finishes after 40 seconds. You might have timeout in the client that doesn't wait for so long. As for the scaling, you are right, the longer the document and the more mentions and entities it contain the more time it will take.
If you want better performance, you should switch to Cassandra as a backend instead of PostgreSQL.

**Comment by mventimi** [comment]
@dmilcevski, thanks for the input!

I have my client set up with no timeout, specifically because the amount of time it takes for AmbiverseNLU to complete is indeterminate. Just going through the logs from overnight, for example, I found this record:
```
2020-01-14 02:02:16,456 [qtp1359212194-26] INFO  entitylinking.preparation.Preparator:53  - Document '231438251653' prepared in 5510.0ms.
2020-01-14 02:11:19,876 [qtp1359212194-26] INFO  nlu.entitylinking.Disambiguator:101  - Document '231438251653' disambiguated in 543420.0ms (17 chunks, 1192 mentions).
2020-01-14 02:11:24,653 [qtp1359212194-26] INFO  entitylinking.preparation.Preparator:53  - Document '231438251653' prepared in 4591.0ms.
2020-01-14 02:15:03,826 [qtp1359212194-26] INFO  nlu.entitylinking.Disambiguator:101  - Document '231438251653' disambiguated in 219172.0ms (17 chunks, 3959 mentions).
```
This is not typical, but is by no means the largest document we've encountered. This particular one was 76,406 characters/11,882 words. Most of the documents we are processing are < 500 characters and process in < 4 seconds, but our average processing time is closer to 10 seconds because of these longer documents and because of the crashes.

We tried installing Cassandra, but could not get it to work using either `docker-compose` or `docker run`. Should I open a separate issue for that?

**Comment by dmilcevski** [comment]
We are working on new dump and fixes for cassandra. I will let you know when we push a new version. 
From your messages there is no errors, just INFO. The last one says it completed in 5mins. Maybe the server does not return anything after 5 mins. Please check the jetty server configurations. If we get the time we will try to fix this. But 70k characters it seems a bit much for the PostgreSQL to handle in reasonable time. Try splitting the document into shorter chunks.

**Comment by mventimi** [comment]
Great to hear about the Cassandra fixes. I'll look forward to them.

In the above case, the document completes in ~13 minutes. Everything seems to be working fine--the client just blocks for 13 minutes until it gets a response to the POST command. It takes a long time, but that's to be expected with such a long document.

We considered splitting up longer documents, but I was concerned about how it could affect the context used for disambiguation. Is there a performance benefit to doing so? I don't mind the long processing times for long documents, and I'd rather not lose the contextual benefits if splitting a document into N pieces is just going to create N requests that take 1/N the time.

**Comment by mventimi** [comment]
I wanted to post an update on how things are going with the changes you suggested. At this point, I'm seeing some unusual behavior with the "memory leak" I referenced. It seems like (1) the leak is only occurring on larger documents, and (2) there exist some documents that cause a crash every time, even immediately after a container restart.

As I mentioned before, I am running on machines that have 64 GB of RAM. Is it possible that I need more memory to handle large documents?

Other than this remaining issue, things are a lot more stable. I do have a lot of questions about performance tuning and optimization. Should I get into them here, or would it be better to put them into a different issue?

**Comment by hoffart** [comment]
Great that things are now working better! Please open a separate ticket for performance issues, it simplifies answering/tracking! Also, a separate ticket with the content of the document that causes a crash is helpful. The memory requirements for documents with thousands of mentions might indeed be an issues, regardless of internal chunking (see below).

Regarding splitting documents: the AIDA entity linking is configured by default to split the documents page-wise, have a look at the `de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.preparation.documentchunking.DocumentChunker` class to see how the default works (and adapt if needed).
